version: '3.8'
services:
  nest-app:
    container_name: sad-dog-api
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "3055:3055"
    depends_on:
      - postgres
    environment:
      DB_URI: ppostgresql://postgres:test123@postgres:5432/postgres
      IS_DB_SSL_MODE: false
      JWT_SECRET: my-32-character-ultra-secure-and-ultra-long-secret
      JWT_EXPIRATION: 60

  postgres:
    container_name: postgres12
    image: postgres:12.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"

  migration:
    container_name: sad-dog-migration
    build:
      context: .
      dockerfile: .dockerfile.migration
    depends_on:
      #- postgres
      postgres:
        condition: service_healthy
    environment:
      DB_URI: ppostgresql://postgres:test123@postgres:5432/postgres?sslmode=disable
      IS_DB_SSL_MODE: false